proPath:
  db:
    host: ${DB_HOST}
    port: ${DB_PORT}
    root: ${DB_ROOT}
    password: ${DB_PASSWORD}
    database: ${DB_DATABASE}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  ai:
    key: ${OPENAI_KEY}
    url: ${OPENAI_URL}
    model: ${OPENAI_MODEL}
  jdbc:
    platform: ${JDBC_PLATFORM}
  mail:
    qq: ${MAIL_QQ}
    token: ${MAIL_TOKEN}

