#?????
DB_HOST=localhost
DB_PORT=3306
DB_ROOT=root
DB_PASSWORD=19805601056Bkj@@
DB_DATABASE=propath
#Redis??
REDIS_HOST=localhost
REDIS_PORT=6379
#OpenAI??
OPENAI_KEY=sk-yw1RYdnX8JseQuM0mDFEVptf4bEBI1Gc6KxPQeuyGLP9BmFk
OPENAI_URL=https://api.chatanywhere.tech
OPENAI_MODEL=gpt-4o-mini
#JDBC??
JDBC_PLATFORM=mariadb
#mail??
MAIL_QQ=3165575650@qq.com
MAIL_TOKEN=qkgdpeallahbdgac
